### ISSUE TITLE
Mac版本一直卡在“获取手机应用列表”页面

### ISSUE THREAD

**Issue by CocoaKier** [TongchengOpenSource/AppScan#31]
## 环境信息
Appscan 版本
> 版本1.0.10 (1.0.10)

电脑版本:
> MacOS 版本13.5.1

手机型号:
> 例如 Mac 网易mumu模拟器v1.9.58

安卓版本:
> 例如 6.0.1

## Bug 描述
> 启动后Appscan，点击开始检测，一直卡在“获取手机应用列表”页面。
多次重启Appscan和mumu模拟器，仍然没有解决。
mumu模拟器也开了root权限。
<img width="1000" alt="iShot_2023-10-20_11 46 02" src="https://github.com/TongchengOpenSource/AppScan/assets/15715942/6ead916a-15bf-4865-b985-86582829a496">

<img width="959" alt="iShot_2023-10-20_11 49 43" src="https://github.com/TongchengOpenSource/AppScan/assets/15715942/d1b819e4-c459-4b94-a116-7f03dd0c74ee">

<img width="966" alt="image" src="https://github.com/TongchengOpenSource/AppScan/assets/15715942/8e5f8ef7-a7f4-4bcb-bb01-0c54d10f3432">

**Comment by ChnMig** [comment]
你好, 目前AppScan暂不支持模拟器, 您可进入链接 模拟器选型 ・ TongchengOpenSource/AppScan ・ Discussion #29 (github.com)<https://github.com/TongchengOpenSource/AppScan/discussions/29> 投票选择希望适配的模拟器品牌, 我们将在投票后进行适配, 感谢使用
________________________________
发件人: CocoaKier ***@***.***>
发送时间: 2023年10月20日 11:55
收件人: TongchengOpenSource/AppScan ***@***.***>
抄送: Subscribed ***@***.***>
主题: [TongchengOpenSource/AppScan] Mac版本一直卡在“获取手机应用列表”页面 (Issue #31)


环境信息

Appscan 版本

版本1.0.10 (1.0.10)

电脑版本:

MacOS 版本13.5.1

手机型号:

例如 Mac 网易mumu模拟器v1.9.58

安卓版本:

例如 6.0.1

Bug 描述

启动后Appscan，点击开始检测，一直卡在“获取手机应用列表”页面。
多次重启Appscan和mumu模拟器，仍然没有解决。
mumu模拟器也开了root权限。

[iShot_2023-10-20_11 46 02]<https://user-images.githubusercontent.com/15715942/276814388-6ead916a-15bf-4865-b985-86582829a496.png> [iShot_2023-10-20_11 49 43] <https://user-images.githubusercontent.com/15715942/276814876-d1b819e4-c459-4b94-a116-7f03dd0c74ee.png>  [image] <https://user-images.githubusercontent.com/15715942/276815524-8e5f8ef7-a7f4-4bcb-bb01-0c54d10f3432.png>

―
