### ISSUE TITLE
点击开始检测，无法拉起应用

### ISSUE THREAD

**Issue by A1rkor** [TongchengOpenSource/AppScan#40]
## Appscan 版本
2.0.0

## 系统版本
小米+magisk

电脑版本:
win11

手机型号:
小米12 pro

安卓版本:
安卓13

## Bug 描述
前面操作都没问题，点击开始检测，无法拉起应用直接黑屏显示小米logo，然后直接锁屏，需要重新选择usb用于,相当于重新插拔了数据线。
![9df8a8d3ccc2e3f01d5413a307f940c](https://github.com/TongchengOpenSource/AppScan/assets/128011364/31a267c4-63e5-43af-9bde-910c62024b59)

**Comment by ChnMig** [comment]
您在使用中是否会一直出现这个问题导致无法正常检测?
我们之前测试会有偶发出现这样的情况, 一般重启后重新连接电脑并重新打开appScan可正常检测, 推测是ROM兼容问题.

**Comment by A1rkor** [comment]
每次检测都是这样，重启也没用，没成功过

**Comment by ChnMig** [comment]
您手头还有其他机器吗? 可以试试其他机器或者下载最新的2.0.0 pre版使用雷电模拟器9检测.
我们收到了您的日志, 但是查看后没有相关信息, 我们手头的机器也没有能够复现的.  我们还是推测与特定的ROM有关. 所以不是同样的环境的话很难排查和处理.
您可以提供一下miui的版本号吗? 还有root管理软件的名称和版本号?  谢谢反馈

**Comment by A1rkor** [comment]
MIUI 14.0.13,magisk 26.1,可以使用雷电模拟器检测
![2AA65EC8B55BC56B88A8D489392BA39A](https://github.com/TongchengOpenSource/AppScan/assets/128011364/c6b05226-ef59-4bfe-9906-5fdb252695d4)
![2A4E722FCFD2750EB5BC52BA5B20B0DE](https://github.com/TongchengOpenSource/AppScan/assets/128011364/5d6596bb-3446-4844-8d39-0ce5de7d9a5e)

**Comment by ChnMig** [comment]
相关信息已采集
