### ISSUE TITLE
[功能建议]mumu模拟器使用adb方法

### ISSUE THREAD

**Issue by yisu1st** [TongchengOpenSource/AppScan#42]
https://mumu.163.com/help/20230504/35047_1086360.html

**Comment by yisu1st** [comment]
![image](https://github.com/TongchengOpenSource/AppScan/assets/144111838/7946608e-a507-472c-96fe-1d9e070d91c4)

**Comment by ChnMig** [comment]
感谢反馈, 大致看了一下MuMu是通过remote的方式去连接adb, 跟目前的连接逻辑有点区别, 我们这边周末评估测试一下可行性, 因为如果是remote的方式还需要用户有一个地方输入设备的ip和port, 涉及到前后端联动, 所以适配进度不会很快, 再次感谢您对AppScan的大力支持

**Comment by yisu1st** [comment]
如果只是适配mumu的话，他的端口是固定的，不多开就是16384，多开就是16384 16480 16512

**Comment by ChnMig** [comment]
如果要做的话直接做支持remote连接了, 先走半步得不偿失, 后续还要改的.

**Comment by yisu1st** [comment]
期待越来越完善！
