### ISSUE TITLE
显示获取手机应用列表失败[BUG]

### ISSUE THREAD

**Issue by xpgdgit** [TongchengOpenSource/AppScan#50]
## Appscan 版本
> 1.0.10
## 系统版本

电脑版本:
> win11 22631.2361
手机型号：
> Pixel2
安卓版本：
> Android 11

## Bug 描述
> 点击连接到设备开始隐私合规检测后，显示获取手机应用列表失败
<img width="751" alt="image" src="https://github.com/TongchengOpenSource/AppScan/assets/30492998/8b8f8ad8-ef08-4f8e-a6f4-2686f7a2df62">

**Comment by ChnMig** [comment]
你好, 请安装最新版后重试
https://github.com/TongchengOpenSource/AppScan/releases/tag/2.1.1

**Comment by xpgdgit** [comment]
> 你好, 请安装最新版后重试 https://github.com/TongchengOpenSource/AppScan/releases/tag/2.1.1

师傅，安装2.1.1版本还是同样的报错

**Comment by xpgdgit** [comment]
师傅，重新安装2.1.1版本，然后切换到特殊引擎后可以了，感谢

**Comment by ChnMig** [comment]
感谢反馈, 普通模式不起作用应该是你测试的APP有一定的反检测能力, 可先使用特殊模式使用, 有问题欢迎随时反馈, 也可加用户群更快交流, 感谢使用
