### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by blackandwhiteforzj** [TongchengOpenSource/AppScan#55]
MacBook-Pro helper % python3 main.py -p 8848
INFO:     Started server process [53740]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8848 (Press CTRL+C to quit)
INFO:     127.0.0.1:60723 - "GET / HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:60723 - "GET / HTTP/1.1" 404 Not Found

**Comment by ChnMig** [comment]
看起来一切正常, 404是因为访问了未注册的路由, 此issue关闭
