### ISSUE TITLE
[BUG]无法连接测试机

### ISSUE THREAD

**Issue by Asi-Moo** [TongchengOpenSource/AppScan#58]
## Appscan 版本
> 请填写目前使用的AppScan的精确版本号

## 系统版本2.1.2

电脑版本:
> 例如 win10

手机型号:
> 例如 Google piex3

安卓版本:
> 例如 安卓9

## Bug 描述
> 请充分描述Bug的现象和复现步骤
![image](https://github.com/TongchengOpenSource/AppScan/assets/35911597/97090656-e5b7-4936-a31f-9da881617288)

无法连接

**Comment by ChnMig** [comment]
你好, 请问您的手机设备是什么? 通过什么方式连接的电脑

**Comment by ChnMig** [comment]
未收到您的进一步反馈, 此issue暂时关闭
