### ISSUE TITLE
[功能建议]增加静态分析功能

### ISSUE THREAD

**Issue by Asi-Moo** [TongchengOpenSource/AppScan#59]
目前版本2.1.2
## 功能建议
> 请充分描述需求背景和功能描述
建议增加静态分析功能，导入apk可以自动分析出权限、sdk之类的统计出来。之前是否有过这个功能，后面改掉了？

**Comment by ChnMig** [comment]
你好, 目前没有静态分析的功能, 之前也没有过, 后面看情况加
