### ISSUE TITLE
[BUG]打标列表显示

### ISSUE THREAD

**Issue by Patricia-oid** [TongchengOpenSource/AppScan#64]
## Appscan 版本
2.1.4

## 系统版本

电脑版本:
> win11

## Bug 描述
检测结果里的“APP是否在列举业务功能时提醒用户不提供个人信息可能带来的影响”在打标列表里没有找到对应显示。
![image](https://github.com/TongchengOpenSource/AppScan/assets/77844375/f3b678d8-9d0b-4b8a-a03a-1cbbebb6acdf)
怀疑问题在step.vue 29行里的那个v-for遍历，从1开始，显示的时候把这项漏了。

**Comment by ChnMig** [comment]
收到, 确认中

**Comment by PrfectDD** [comment]
确实会漏掉每页的第一个，这是前四页漏掉的项
{
    "id": "4bf5ced58621b6aec5c3037b2ffe56b2",
    "project": "APP是否在未同意隐私政策情况下有申请权限的行为",
    "standard": "用户首次使用APP时，在未向用户明示申请权限的目的并征得同意前，就开始向用户申请权限的行为属于未经用户同意收集个人信息。",
    "riskLevel": 2,
    "page": 1.0,
    "okText": "通过（同意隐私政策前无权限申请） ",
    "failText": "不通过（同意隐私政策前存在权限申请）",
    "type": "收集规则"
},

{
    "id": "9141a84c678b2b522be7c051bfd0a432",
    "project": "APP是否以默认选择同意隐私政策等非明示方式征求用户同意",
    "standard": "1、未主动提醒用户阅读隐私政策。2、APP注册登录或其他服务在征求用户同意环节，不得默认勾选隐私政策，需要用户主动勾选。3、APP注册登录服务在征求用户同意环节，不采取登录即代表同意或者无隐私政策链接等非明示方式。",
    "riskLevel": 2,
    "page": 2.0,
    "okText": "通过（不存在默认同意）",
    "failText": "不通过（存在默认同意）",
    "type": "明示同意"
},


{
    "id": "b3764109bcd49711613dd4373e9c94d1",
    "project": "APP是否在列举业务功能时提醒用户不提供个人信息可能带来的影响",
    "standard": "在描述各业务功能所收集的个人信息时，需要单独提醒用户不提供个人信息所带来的影响。",
    "riskLevel": 0,
    "page": 3.0,
    "okText": "通过（在列举业务功能时已提醒用户不提供个人信息可能带来的影响）",
    "failText": "不通过（在列举业务功能时未提醒用户不提供个人信息可能带来的影响）",
    "type": "使用规则"
},
{
    "id": "420e283f9ed83fc3a27320a7b186b401",
    "project": "APP是否明示个人信息存储及超期处理方式",
    "standard": "在隐私政策应对个人信息存放地域（国内、国外）；存储期限（法律规定范围内最短期限或明确期限）、超期处理方式（删除或匿名化处理）进行明确的说明。",
    "riskLevel": 0,
    "page": 4.0,
    "okText": "通过（已明示个人信息存储及超期处理方式）",
    "failText": "不通过（未明示个人信息存储及超期处理方式）",
    "type": "保存规则"
},

**Comment by ChnMig** [comment]
> 确实会漏掉每页的第一个，这是前四页漏掉的项 { "id": "4bf5ced58621b6aec5c3037b2ffe56b2", "project": "APP是否在未同意隐私政策情况下有申请权限的行为", "standard": "用户首次使用APP时，在未向用户明示申请权限的目的并征得同意前，就开始向用户申请权限的行为属于未经用户同意收集个人信息。", "riskLevel": 2, "page": 1.0, "okText": "通过（同意隐私政策前无权限申请） ", "failText": "不通过（同意隐私政策前存在权限申请）", "type": "收集规则" },
> 
> { "id": "9141a84c678b2b522be7c051bfd0a432", "project": "APP是否以默认选择同意隐私政策等非明示方式征求用户同意", "standard": "1、未主动提醒用户阅读隐私政策。2、APP注册登录或其他服务在征求用户同意环节，不得默认勾选隐私政策，需要用户主动勾选。3、APP注册登录服务在征求用户同意环节，不采取登录即代表同意或者无隐私政策链接等非明示方式。", "riskLevel": 2, "page": 2.0, "okText": "通过（不存在默认同意）", "failText": "不通过（存在默认同意）", "type": "明示同意" },
> 
> { "id": "b3764109bcd49711613dd4373e9c94d1", "project": "APP是否在列举业务功能时提醒用户不提供个人信息可能带来的影响", "standard": "在描述各业务功能所收集的个人信息时，需要单独提醒用户不提供个人信息所带来的影响。", "riskLevel": 0, "page": 3.0, "okText": "通过（在列举业务功能时已提醒用户不提供个人信息可能带来的影响）", "failText": "不通过（在列举业务功能时未提醒用户不提供个人信息可能带来的影响）", "type": "使用规则" }, { "id": "420e283f9ed83fc3a27320a7b186b401", "project": "APP是否明示个人信息存储及超期处理方式", "standard": "在隐私政策应对个人信息存放地域（国内、国外）；存储期限（法律规定范围内最短期限或明确期限）、超期处理方式（删除或匿名化处理）进行明确的说明。", "riskLevel": 0, "page": 4.0, "okText": "通过（已明示个人信息存储及超期处理方式）", "failText": "不通过（未明示个人信息存储及超期处理方式）", "type": "保存规则" },

感谢, 本周末发布新版本修复

**Comment by ChnMig** [comment]
已发布更新 2.1.5
