### ISSUE TITLE
[BUG]android.location.Location.getTime()是否算获取定位权限

### ISSUE THREAD

**Issue by li-hahaha** [TongchengOpenSource/AppScan#67]
## Appscan 版本
> 2.1.4

## 系统版本

电脑版本:
> win10

手机型号:
> 雷电模拟器

## Bug 描述
> 项目在获取定位权限时，获取次数较多，其中android.location.Location.getTime()调用一次，也算作获取一次定位，不知是否合理。
因此在项目中操作打开地图定位时（操作是点击对应按钮），初始化高德SDK并获取地图，就获取了30多次定位，其中包括10多次getTime。

**Comment by ChnMig** [comment]
感谢反馈, 我们排查一下

**Comment by ChnMig** [comment]
https://github.com/TongchengOpenSource/AppScan/commit/1ea811b0813a5544c829ae1dbf9e9c08246c8448   下版本修复
