### ISSUE TITLE
手机架构不支持

### ISSUE THREAD

**Issue by wingkingbobo** [TongchengOpenSource/AppScan#70]
## Appscan 版本
> 2.1.5

## 系统版本

电脑版本:
> win10专业版，Intel(R) Core(TM) i7-10510U CPU

手机型号:
> MuMu模拟器 v3.9.0 (3034)

安卓版本:
> Android 12

## Bug 描述
1.打开mumu模拟器，打开待测试app（arm64-v8a）
2.命令行输入 `adb.exe connect 127.0.0.1:7555`
3.AppScan点击 `请点击这里连接到设备开始隐私合规检测`，弹窗报错如下：
> 初始化错误: ('手机架构不支持', '')

**Comment by ChnMig** [comment]
暂不支持mumu
